//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MargieBot.TrycorderWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ScannerInterfaceDefinition", Namespace="http://tempuri.org/")]
    public partial class ScannerClass : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ScanResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ScanAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadAWSCredentialsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveBadProfilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializeOperationCompleted;
        
        private System.Threading.SendOrPostCallback LastScanOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetComponentDataTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetColumnVisSettingOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetColumnVisSettingOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback FilterDataTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback FilterDataTablebyColOperationCompleted;
        
        private System.Threading.SendOrPostCallback FilterScannerDataTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback FilterScannerDataTablebyColOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetRegionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback setProfileStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProfilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBadProfilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetComponentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDetailedStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetComponentScanBitOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ScannerClass() {
            this.Url = global::MargieBot.Properties.Settings.Default.MargieBot_TrycorderWebReference_ScannerClass;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ScanResultsCompletedEventHandler ScanResultsCompleted;
        
        /// <remarks/>
        public event ScanAllCompletedEventHandler ScanAllCompleted;
        
        /// <remarks/>
        public event LoadAWSCredentialsCompletedEventHandler LoadAWSCredentialsCompleted;
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event RemoveBadProfilesCompletedEventHandler RemoveBadProfilesCompleted;
        
        /// <remarks/>
        public event InitializeCompletedEventHandler InitializeCompleted;
        
        /// <remarks/>
        public event LastScanCompletedEventHandler LastScanCompleted;
        
        /// <remarks/>
        public event GetComponentDataTableCompletedEventHandler GetComponentDataTableCompleted;
        
        /// <remarks/>
        public event GetColumnVisSettingCompletedEventHandler GetColumnVisSettingCompleted;
        
        /// <remarks/>
        public event SetColumnVisSettingCompletedEventHandler SetColumnVisSettingCompleted;
        
        /// <remarks/>
        public event GetStatusCompletedEventHandler GetStatusCompleted;
        
        /// <remarks/>
        public event FilterDataTableCompletedEventHandler FilterDataTableCompleted;
        
        /// <remarks/>
        public event FilterDataTablebyColCompletedEventHandler FilterDataTablebyColCompleted;
        
        /// <remarks/>
        public event FilterScannerDataTableCompletedEventHandler FilterScannerDataTableCompleted;
        
        /// <remarks/>
        public event FilterScannerDataTablebyColCompletedEventHandler FilterScannerDataTablebyColCompleted;
        
        /// <remarks/>
        public event SetRegionStatusCompletedEventHandler SetRegionStatusCompleted;
        
        /// <remarks/>
        public event setProfileStatusCompletedEventHandler setProfileStatusCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        public event GetProfilesCompletedEventHandler GetProfilesCompleted;
        
        /// <remarks/>
        public event GetBadProfilesCompletedEventHandler GetBadProfilesCompleted;
        
        /// <remarks/>
        public event GetRegionsCompletedEventHandler GetRegionsCompleted;
        
        /// <remarks/>
        public event GetComponentsCompletedEventHandler GetComponentsCompleted;
        
        /// <remarks/>
        public event GetDetailedStatusCompletedEventHandler GetDetailedStatusCompleted;
        
        /// <remarks/>
        public event SetComponentScanBitCompletedEventHandler SetComponentScanBitCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/ScanResults", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet ScanResults() {
            object[] results = this.Invoke("ScanResults", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ScanResultsAsync() {
            this.ScanResultsAsync(null);
        }
        
        /// <remarks/>
        public void ScanResultsAsync(object userState) {
            if ((this.ScanResultsOperationCompleted == null)) {
                this.ScanResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnScanResultsOperationCompleted);
            }
            this.InvokeAsync("ScanResults", new object[0], this.ScanResultsOperationCompleted, userState);
        }
        
        private void OnScanResultsOperationCompleted(object arg) {
            if ((this.ScanResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ScanResultsCompleted(this, new ScanResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/ScanAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ScanAll() {
            object[] results = this.Invoke("ScanAll", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ScanAllAsync() {
            this.ScanAllAsync(null);
        }
        
        /// <remarks/>
        public void ScanAllAsync(object userState) {
            if ((this.ScanAllOperationCompleted == null)) {
                this.ScanAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnScanAllOperationCompleted);
            }
            this.InvokeAsync("ScanAll", new object[0], this.ScanAllOperationCompleted, userState);
        }
        
        private void OnScanAllOperationCompleted(object arg) {
            if ((this.ScanAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ScanAllCompleted(this, new ScanAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/LoadAWSCredentials", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LoadAWSCredentials([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string credentialfile) {
            object[] results = this.Invoke("LoadAWSCredentials", new object[] {
                        credentialfile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoadAWSCredentialsAsync(string credentialfile) {
            this.LoadAWSCredentialsAsync(credentialfile, null);
        }
        
        /// <remarks/>
        public void LoadAWSCredentialsAsync(string credentialfile, object userState) {
            if ((this.LoadAWSCredentialsOperationCompleted == null)) {
                this.LoadAWSCredentialsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadAWSCredentialsOperationCompleted);
            }
            this.InvokeAsync("LoadAWSCredentials", new object[] {
                        credentialfile}, this.LoadAWSCredentialsOperationCompleted, userState);
        }
        
        private void OnLoadAWSCredentialsOperationCompleted(object arg) {
            if ((this.LoadAWSCredentialsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadAWSCredentialsCompleted(this, new LoadAWSCredentialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/RemoveBadProfiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RemoveBadProfiles() {
            object[] results = this.Invoke("RemoveBadProfiles", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveBadProfilesAsync() {
            this.RemoveBadProfilesAsync(null);
        }
        
        /// <remarks/>
        public void RemoveBadProfilesAsync(object userState) {
            if ((this.RemoveBadProfilesOperationCompleted == null)) {
                this.RemoveBadProfilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveBadProfilesOperationCompleted);
            }
            this.InvokeAsync("RemoveBadProfiles", new object[0], this.RemoveBadProfilesOperationCompleted, userState);
        }
        
        private void OnRemoveBadProfilesOperationCompleted(object arg) {
            if ((this.RemoveBadProfilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveBadProfilesCompleted(this, new RemoveBadProfilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/Initialize", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Initialize() {
            object[] results = this.Invoke("Initialize", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InitializeAsync() {
            this.InitializeAsync(null);
        }
        
        /// <remarks/>
        public void InitializeAsync(object userState) {
            if ((this.InitializeOperationCompleted == null)) {
                this.InitializeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeOperationCompleted);
            }
            this.InvokeAsync("Initialize", new object[0], this.InitializeOperationCompleted, userState);
        }
        
        private void OnInitializeOperationCompleted(object arg) {
            if ((this.InitializeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeCompleted(this, new InitializeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/LastScan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastScan() {
            object[] results = this.Invoke("LastScan", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LastScanAsync() {
            this.LastScanAsync(null);
        }
        
        /// <remarks/>
        public void LastScanAsync(object userState) {
            if ((this.LastScanOperationCompleted == null)) {
                this.LastScanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLastScanOperationCompleted);
            }
            this.InvokeAsync("LastScan", new object[0], this.LastScanOperationCompleted, userState);
        }
        
        private void OnLastScanOperationCompleted(object arg) {
            if ((this.LastScanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LastScanCompleted(this, new LastScanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/GetComponentDataTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetComponentDataTable([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string component) {
            object[] results = this.Invoke("GetComponentDataTable", new object[] {
                        component});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetComponentDataTableAsync(string component) {
            this.GetComponentDataTableAsync(component, null);
        }
        
        /// <remarks/>
        public void GetComponentDataTableAsync(string component, object userState) {
            if ((this.GetComponentDataTableOperationCompleted == null)) {
                this.GetComponentDataTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetComponentDataTableOperationCompleted);
            }
            this.InvokeAsync("GetComponentDataTable", new object[] {
                        component}, this.GetComponentDataTableOperationCompleted, userState);
        }
        
        private void OnGetComponentDataTableOperationCompleted(object arg) {
            if ((this.GetComponentDataTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetComponentDataTableCompleted(this, new GetComponentDataTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/GetColumnVisSetting", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringboolean", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[] GetColumnVisSetting([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string component) {
            object[] results = this.Invoke("GetColumnVisSetting", new object[] {
                        component});
            return ((ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[])(results[0]));
        }
        
        /// <remarks/>
        public void GetColumnVisSettingAsync(string component) {
            this.GetColumnVisSettingAsync(component, null);
        }
        
        /// <remarks/>
        public void GetColumnVisSettingAsync(string component, object userState) {
            if ((this.GetColumnVisSettingOperationCompleted == null)) {
                this.GetColumnVisSettingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetColumnVisSettingOperationCompleted);
            }
            this.InvokeAsync("GetColumnVisSetting", new object[] {
                        component}, this.GetColumnVisSettingOperationCompleted, userState);
        }
        
        private void OnGetColumnVisSettingOperationCompleted(object arg) {
            if ((this.GetColumnVisSettingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetColumnVisSettingCompleted(this, new GetColumnVisSettingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/SetColumnVisSetting", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetColumnVisSetting([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string component, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string column, bool visibility, [System.Xml.Serialization.XmlIgnoreAttribute()] bool visibilitySpecified) {
            this.Invoke("SetColumnVisSetting", new object[] {
                        component,
                        column,
                        visibility,
                        visibilitySpecified});
        }
        
        /// <remarks/>
        public void SetColumnVisSettingAsync(string component, string column, bool visibility, bool visibilitySpecified) {
            this.SetColumnVisSettingAsync(component, column, visibility, visibilitySpecified, null);
        }
        
        /// <remarks/>
        public void SetColumnVisSettingAsync(string component, string column, bool visibility, bool visibilitySpecified, object userState) {
            if ((this.SetColumnVisSettingOperationCompleted == null)) {
                this.SetColumnVisSettingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetColumnVisSettingOperationCompleted);
            }
            this.InvokeAsync("SetColumnVisSetting", new object[] {
                        component,
                        column,
                        visibility,
                        visibilitySpecified}, this.SetColumnVisSettingOperationCompleted, userState);
        }
        
        private void OnSetColumnVisSettingOperationCompleted(object arg) {
            if ((this.SetColumnVisSettingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetColumnVisSettingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/GetStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetStatus() {
            object[] results = this.Invoke("GetStatus", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusAsync() {
            this.GetStatusAsync(null);
        }
        
        /// <remarks/>
        public void GetStatusAsync(object userState) {
            if ((this.GetStatusOperationCompleted == null)) {
                this.GetStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusOperationCompleted);
            }
            this.InvokeAsync("GetStatus", new object[0], this.GetStatusOperationCompleted, userState);
        }
        
        private void OnGetStatusOperationCompleted(object arg) {
            if ((this.GetStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusCompleted(this, new GetStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/FilterDataTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable FilterDataTable([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Data.DataTable Table2Filter, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string filterstring, bool caseinsensitive, [System.Xml.Serialization.XmlIgnoreAttribute()] bool caseinsensitiveSpecified) {
            object[] results = this.Invoke("FilterDataTable", new object[] {
                        Table2Filter,
                        filterstring,
                        caseinsensitive,
                        caseinsensitiveSpecified});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void FilterDataTableAsync(System.Data.DataTable Table2Filter, string filterstring, bool caseinsensitive, bool caseinsensitiveSpecified) {
            this.FilterDataTableAsync(Table2Filter, filterstring, caseinsensitive, caseinsensitiveSpecified, null);
        }
        
        /// <remarks/>
        public void FilterDataTableAsync(System.Data.DataTable Table2Filter, string filterstring, bool caseinsensitive, bool caseinsensitiveSpecified, object userState) {
            if ((this.FilterDataTableOperationCompleted == null)) {
                this.FilterDataTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFilterDataTableOperationCompleted);
            }
            this.InvokeAsync("FilterDataTable", new object[] {
                        Table2Filter,
                        filterstring,
                        caseinsensitive,
                        caseinsensitiveSpecified}, this.FilterDataTableOperationCompleted, userState);
        }
        
        private void OnFilterDataTableOperationCompleted(object arg) {
            if ((this.FilterDataTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FilterDataTableCompleted(this, new FilterDataTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/FilterDataTablebyCol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable FilterDataTablebyCol([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Data.DataTable Table2Filter, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string column2filter, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string filterstring, bool caseinsensitive, [System.Xml.Serialization.XmlIgnoreAttribute()] bool caseinsensitiveSpecified) {
            object[] results = this.Invoke("FilterDataTablebyCol", new object[] {
                        Table2Filter,
                        column2filter,
                        filterstring,
                        caseinsensitive,
                        caseinsensitiveSpecified});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void FilterDataTablebyColAsync(System.Data.DataTable Table2Filter, string column2filter, string filterstring, bool caseinsensitive, bool caseinsensitiveSpecified) {
            this.FilterDataTablebyColAsync(Table2Filter, column2filter, filterstring, caseinsensitive, caseinsensitiveSpecified, null);
        }
        
        /// <remarks/>
        public void FilterDataTablebyColAsync(System.Data.DataTable Table2Filter, string column2filter, string filterstring, bool caseinsensitive, bool caseinsensitiveSpecified, object userState) {
            if ((this.FilterDataTablebyColOperationCompleted == null)) {
                this.FilterDataTablebyColOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFilterDataTablebyColOperationCompleted);
            }
            this.InvokeAsync("FilterDataTablebyCol", new object[] {
                        Table2Filter,
                        column2filter,
                        filterstring,
                        caseinsensitive,
                        caseinsensitiveSpecified}, this.FilterDataTablebyColOperationCompleted, userState);
        }
        
        private void OnFilterDataTablebyColOperationCompleted(object arg) {
            if ((this.FilterDataTablebyColCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FilterDataTablebyColCompleted(this, new FilterDataTablebyColCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/FilterScannerDataTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable FilterScannerDataTable([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Table2Filter, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string filterstring, bool caseinsensitive, [System.Xml.Serialization.XmlIgnoreAttribute()] bool caseinsensitiveSpecified) {
            object[] results = this.Invoke("FilterScannerDataTable", new object[] {
                        Table2Filter,
                        filterstring,
                        caseinsensitive,
                        caseinsensitiveSpecified});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void FilterScannerDataTableAsync(string Table2Filter, string filterstring, bool caseinsensitive, bool caseinsensitiveSpecified) {
            this.FilterScannerDataTableAsync(Table2Filter, filterstring, caseinsensitive, caseinsensitiveSpecified, null);
        }
        
        /// <remarks/>
        public void FilterScannerDataTableAsync(string Table2Filter, string filterstring, bool caseinsensitive, bool caseinsensitiveSpecified, object userState) {
            if ((this.FilterScannerDataTableOperationCompleted == null)) {
                this.FilterScannerDataTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFilterScannerDataTableOperationCompleted);
            }
            this.InvokeAsync("FilterScannerDataTable", new object[] {
                        Table2Filter,
                        filterstring,
                        caseinsensitive,
                        caseinsensitiveSpecified}, this.FilterScannerDataTableOperationCompleted, userState);
        }
        
        private void OnFilterScannerDataTableOperationCompleted(object arg) {
            if ((this.FilterScannerDataTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FilterScannerDataTableCompleted(this, new FilterScannerDataTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/FilterScannerDataTablebyCol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable FilterScannerDataTablebyCol([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Table2Filter, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string column2filter, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string filterstring, bool caseinsensitive, [System.Xml.Serialization.XmlIgnoreAttribute()] bool caseinsensitiveSpecified) {
            object[] results = this.Invoke("FilterScannerDataTablebyCol", new object[] {
                        Table2Filter,
                        column2filter,
                        filterstring,
                        caseinsensitive,
                        caseinsensitiveSpecified});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void FilterScannerDataTablebyColAsync(string Table2Filter, string column2filter, string filterstring, bool caseinsensitive, bool caseinsensitiveSpecified) {
            this.FilterScannerDataTablebyColAsync(Table2Filter, column2filter, filterstring, caseinsensitive, caseinsensitiveSpecified, null);
        }
        
        /// <remarks/>
        public void FilterScannerDataTablebyColAsync(string Table2Filter, string column2filter, string filterstring, bool caseinsensitive, bool caseinsensitiveSpecified, object userState) {
            if ((this.FilterScannerDataTablebyColOperationCompleted == null)) {
                this.FilterScannerDataTablebyColOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFilterScannerDataTablebyColOperationCompleted);
            }
            this.InvokeAsync("FilterScannerDataTablebyCol", new object[] {
                        Table2Filter,
                        column2filter,
                        filterstring,
                        caseinsensitive,
                        caseinsensitiveSpecified}, this.FilterScannerDataTablebyColOperationCompleted, userState);
        }
        
        private void OnFilterScannerDataTablebyColOperationCompleted(object arg) {
            if ((this.FilterScannerDataTablebyColCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FilterScannerDataTablebyColCompleted(this, new FilterScannerDataTablebyColCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/SetRegionStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetRegionStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string region, bool state, [System.Xml.Serialization.XmlIgnoreAttribute()] bool stateSpecified) {
            this.Invoke("SetRegionStatus", new object[] {
                        region,
                        state,
                        stateSpecified});
        }
        
        /// <remarks/>
        public void SetRegionStatusAsync(string region, bool state, bool stateSpecified) {
            this.SetRegionStatusAsync(region, state, stateSpecified, null);
        }
        
        /// <remarks/>
        public void SetRegionStatusAsync(string region, bool state, bool stateSpecified, object userState) {
            if ((this.SetRegionStatusOperationCompleted == null)) {
                this.SetRegionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetRegionStatusOperationCompleted);
            }
            this.InvokeAsync("SetRegionStatus", new object[] {
                        region,
                        state,
                        stateSpecified}, this.SetRegionStatusOperationCompleted, userState);
        }
        
        private void OnSetRegionStatusOperationCompleted(object arg) {
            if ((this.SetRegionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetRegionStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/setProfileStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setProfileStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string aprofile, bool state, [System.Xml.Serialization.XmlIgnoreAttribute()] bool stateSpecified) {
            this.Invoke("setProfileStatus", new object[] {
                        aprofile,
                        state,
                        stateSpecified});
        }
        
        /// <remarks/>
        public void setProfileStatusAsync(string aprofile, bool state, bool stateSpecified) {
            this.setProfileStatusAsync(aprofile, state, stateSpecified, null);
        }
        
        /// <remarks/>
        public void setProfileStatusAsync(string aprofile, bool state, bool stateSpecified, object userState) {
            if ((this.setProfileStatusOperationCompleted == null)) {
                this.setProfileStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetProfileStatusOperationCompleted);
            }
            this.InvokeAsync("setProfileStatus", new object[] {
                        aprofile,
                        state,
                        stateSpecified}, this.setProfileStatusOperationCompleted, userState);
        }
        
        private void OnsetProfileStatusOperationCompleted(object arg) {
            if ((this.setProfileStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setProfileStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/GetProfiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringboolean", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[] GetProfiles() {
            object[] results = this.Invoke("GetProfiles", new object[0]);
            return ((ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProfilesAsync() {
            this.GetProfilesAsync(null);
        }
        
        /// <remarks/>
        public void GetProfilesAsync(object userState) {
            if ((this.GetProfilesOperationCompleted == null)) {
                this.GetProfilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfilesOperationCompleted);
            }
            this.InvokeAsync("GetProfiles", new object[0], this.GetProfilesOperationCompleted, userState);
        }
        
        private void OnGetProfilesOperationCompleted(object arg) {
            if ((this.GetProfilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProfilesCompleted(this, new GetProfilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/GetBadProfiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] GetBadProfiles() {
            object[] results = this.Invoke("GetBadProfiles", new object[0]);
            return ((ArrayOfKeyValueOfstringstringKeyValueOfstringstring[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBadProfilesAsync() {
            this.GetBadProfilesAsync(null);
        }
        
        /// <remarks/>
        public void GetBadProfilesAsync(object userState) {
            if ((this.GetBadProfilesOperationCompleted == null)) {
                this.GetBadProfilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBadProfilesOperationCompleted);
            }
            this.InvokeAsync("GetBadProfiles", new object[0], this.GetBadProfilesOperationCompleted, userState);
        }
        
        private void OnGetBadProfilesOperationCompleted(object arg) {
            if ((this.GetBadProfilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBadProfilesCompleted(this, new GetBadProfilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/GetRegions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringboolean", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[] GetRegions() {
            object[] results = this.Invoke("GetRegions", new object[0]);
            return ((ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRegionsAsync() {
            this.GetRegionsAsync(null);
        }
        
        /// <remarks/>
        public void GetRegionsAsync(object userState) {
            if ((this.GetRegionsOperationCompleted == null)) {
                this.GetRegionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegionsOperationCompleted);
            }
            this.InvokeAsync("GetRegions", new object[0], this.GetRegionsOperationCompleted, userState);
        }
        
        private void OnGetRegionsOperationCompleted(object arg) {
            if ((this.GetRegionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegionsCompleted(this, new GetRegionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/GetComponents", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringboolean", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[] GetComponents() {
            object[] results = this.Invoke("GetComponents", new object[0]);
            return ((ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[])(results[0]));
        }
        
        /// <remarks/>
        public void GetComponentsAsync() {
            this.GetComponentsAsync(null);
        }
        
        /// <remarks/>
        public void GetComponentsAsync(object userState) {
            if ((this.GetComponentsOperationCompleted == null)) {
                this.GetComponentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetComponentsOperationCompleted);
            }
            this.InvokeAsync("GetComponents", new object[0], this.GetComponentsOperationCompleted, userState);
        }
        
        private void OnGetComponentsOperationCompleted(object arg) {
            if ((this.GetComponentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetComponentsCompleted(this, new GetComponentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/GetDetailedStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetDetailedStatus() {
            object[] results = this.Invoke("GetDetailedStatus", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDetailedStatusAsync() {
            this.GetDetailedStatusAsync(null);
        }
        
        /// <remarks/>
        public void GetDetailedStatusAsync(object userState) {
            if ((this.GetDetailedStatusOperationCompleted == null)) {
                this.GetDetailedStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDetailedStatusOperationCompleted);
            }
            this.InvokeAsync("GetDetailedStatus", new object[0], this.GetDetailedStatusOperationCompleted, userState);
        }
        
        private void OnGetDetailedStatusOperationCompleted(object arg) {
            if ((this.GetDetailedStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDetailedStatusCompleted(this, new GetDetailedStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScannerInterfaceDefinition/SetComponentScanBit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetComponentScanBit([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string component, bool state, [System.Xml.Serialization.XmlIgnoreAttribute()] bool stateSpecified) {
            this.Invoke("SetComponentScanBit", new object[] {
                        component,
                        state,
                        stateSpecified});
        }
        
        /// <remarks/>
        public void SetComponentScanBitAsync(string component, bool state, bool stateSpecified) {
            this.SetComponentScanBitAsync(component, state, stateSpecified, null);
        }
        
        /// <remarks/>
        public void SetComponentScanBitAsync(string component, bool state, bool stateSpecified, object userState) {
            if ((this.SetComponentScanBitOperationCompleted == null)) {
                this.SetComponentScanBitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetComponentScanBitOperationCompleted);
            }
            this.InvokeAsync("SetComponentScanBit", new object[] {
                        component,
                        state,
                        stateSpecified}, this.SetComponentScanBitOperationCompleted, userState);
        }
        
        private void OnSetComponentScanBitOperationCompleted(object arg) {
            if ((this.SetComponentScanBitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetComponentScanBitCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean {
        
        private string keyField;
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ScannerEngine")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ScanResultsCompletedEventHandler(object sender, ScanResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ScanResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ScanResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ScanAllCompletedEventHandler(object sender, ScanAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ScanAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ScanAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LoadAWSCredentialsCompletedEventHandler(object sender, LoadAWSCredentialsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadAWSCredentialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadAWSCredentialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RemoveBadProfilesCompletedEventHandler(object sender, RemoveBadProfilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveBadProfilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveBadProfilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void InitializeCompletedEventHandler(object sender, InitializeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitializeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitializeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LastScanCompletedEventHandler(object sender, LastScanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LastScanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LastScanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetComponentDataTableCompletedEventHandler(object sender, GetComponentDataTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetComponentDataTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetComponentDataTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetColumnVisSettingCompletedEventHandler(object sender, GetColumnVisSettingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetColumnVisSettingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetColumnVisSettingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SetColumnVisSettingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetStatusCompletedEventHandler(object sender, GetStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FilterDataTableCompletedEventHandler(object sender, FilterDataTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FilterDataTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FilterDataTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FilterDataTablebyColCompletedEventHandler(object sender, FilterDataTablebyColCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FilterDataTablebyColCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FilterDataTablebyColCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FilterScannerDataTableCompletedEventHandler(object sender, FilterScannerDataTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FilterScannerDataTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FilterScannerDataTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FilterScannerDataTablebyColCompletedEventHandler(object sender, FilterScannerDataTablebyColCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FilterScannerDataTablebyColCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FilterScannerDataTablebyColCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SetRegionStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void setProfileStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetProfilesCompletedEventHandler(object sender, GetProfilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProfilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProfilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetBadProfilesCompletedEventHandler(object sender, GetBadProfilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBadProfilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBadProfilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrayOfKeyValueOfstringstringKeyValueOfstringstring[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRegionsCompletedEventHandler(object sender, GetRegionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetComponentsCompletedEventHandler(object sender, GetComponentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetComponentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetComponentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrayOfKeyValueOfstringbooleanKeyValueOfstringboolean[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDetailedStatusCompletedEventHandler(object sender, GetDetailedStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDetailedStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDetailedStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SetComponentScanBitCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591